### PR TITLE
[ImgBot] Optimize images (#1)

### PR DESCRIPTION
**Pull request by jsbentley34**
*Total -- 184.84kb -> 181.69kb (1.7%)

/website/images/logos.png -- 8.32kb -> 7.62kb (8.4%)
/website/images/logo-shape.svg -- 2.40kb -> 2.21kb (8.05%)
/website/images/raspberry-pi.svg -- 165.21kb -> 162.97kb (1.36%)
/website/images/logo-masked.svg -- 4.61kb -> 4.60kb (0.25%)
/website/images/logo-new.svg -- 4.29kb -> 4.29kb (0.07%)

Signed-off-by: ImgBotApp <ImgBotHelp@gmail.com>

Co-authored-by: Imgbot <help@imgbot.net>

### CODE REVIEW

**Comment by jsbentley34** [comment]
Brnach

**Comment by jsbentley34** [comment]
I

**Comment by nfarina** [comment]
Hi! It looks like this PR adds some Github workflow stuff that I'm unfamiliar with, as well as some smallish optimizations to the handful of images in this repo?

**Comment by alexindigo** [comment]
@nfarina It's just sample/boilerplate workflow scripts that won't work without adjustments. Looks like some failed changes attempt by some bot-in-development. Should be fine to close.

**Comment by nfarina** [comment]
@alexindigo Thanks for catching that; I didn't click on the user to investigate. Makes sense to me!

**Pull request closed without merging**
