### PR TITLE
Add support for more Sonos speakers

### LINKED ISSUE #18: sonos being detected but does not react
I get this when starting up:

````
> homebridge@0.0.0 start /Users/max/code/homekit/homebridge
> node app.js

Starting HomeBridge server...
Loading 0 platforms...
Loading 1 accessories...
[Speakers] Initializing Sonos accessory...
TCP server accepting connection on port: 51826
HAP Server is listening
[Speakers] Found device at 192.168.1.140
[Speakers] Found device at 192.168.1.145
[Speakers] Found device at 192.168.1.148
[Speakers] Found device at 192.168.1.159
[Speakers] Found device at 192.168.1.129
[Speakers] Found device at 192.168.1.117
[Speakers] Found device at 192.168.1.136
[Speakers] Found device at 192.168.1.151
New Session 55966
Server Connection Established 61027
Start Verify M1
Verify M1 Finished
Start Verify M3
M3: Verify Success
{ characteristics: [ { aid: 1, iid: 9, ev: true } ] }
Enable Event: true
{ characteristics: [ { aid: 1, iid: 9, value: false } ] }
````

but when I use insteon+ or siri to turn speakers on or off then I get this in the log:

````
[Speakers] No device found (yet?)
````
any idea on how to fix that ?

### PR DESCRIPTION
**Pull request by maxandersen**
Add's detection of Play:1, Connect and Play:5

Fixes #18.

### CODE REVIEW

**Comment by nfarina** [comment]
Do we get any kind of description about what device is what? One problem I can see in your case is - when you say "turn on the speakers" do you mean all of them? I suppose it depends how many zones you've setup?

**Comment by maxandersen** [comment]
I haven't added any additional descriptions, just made it so they get detected.

But even with these I haven't figured out how it decides which speakers it wants to mute - it seem to be somewhat random.

**Comment by tocks53** [comment]
+1 for the play 1

**Comment by bezzers** [comment]
My latest pull request (#77) may supersede this because it should discover and add all non-bridge Sonos devices as a platform.

**Comment by nfarina** [comment]
@maxandersen Does #77 (now in master) make things work for you?

**Comment by nfarina** [comment]
Closing for now since we have Sonos as a platform - it should theoretically support the same features as this PR.

**Pull request closed without merging**
