### PR TITLE
Add support for FirmwareRevision and HardwareRevision characteristics

### PR DESCRIPTION
**Pull request by schmittx**
Adds support for FirmwareRevision (required) and HardwareRevision
(optional) characteristics to both Homebridge itself and accessory platforms/plugins.

### CODE REVIEW

**Comment by nfarina** [comment]
Looks good, thanks!

**Comment by simont77** [comment]
Hi, if I understood well, FirmwareRevision has to be manually set in config.json file. This means that one have to update the config file every time homebridge updates. Would it be possible to automatically set the FirmwareRevision characteristic using actual homebridge version? Thanks

**Comment by nfarina** [comment]
Good point - why would Homebridge users ever need to set these manually?

**Comment by schmittx** [comment]
All valid points, hard coding and removing it from the config is easy but I don't know how to link it to the `package.json` (NPM) version. Any suggestions?

**Comment by simont77** [comment]
Same for me, this is why I asked.

**Comment by nfarina** [comment]
You mean like `require('./package.json').version`?

**Comment by schmittx** [comment]
@nfarina Ha, yeah...sorry, I'm still new to Node...I'll update/confirm this weekend and submit a new PR

**Comment by schmittx** [comment]
Check #1554, should be good to go now.

**Pull request merged**
