### PR TITLE
Platform shim for Fibaro Home Center 2

### PR DESCRIPTION
**Pull request by ilcato**
Works:

+Fibaro Dimmer and dimmer 2 (and in general com.fibaro.multilevelSwitch)
+Fibaro RollerShutter FGRM222 and FGR 221 (com.fibaro.FGRM222, com.fibaro.FGR221)
+Fibaro Relè (and in general com.fibaro.binarySwitch)
+Fibaro Motion Sensor (com.fibaro.motionSensor and com.fibaro.FGMS001)
+Fibaro Temperature sensor (com.fibaro.temperatureSensor)
+Fibaro Door/Window sensor (com.fibaro.doorSensor)
+Fibaro Light Sensor (com.fibaro.lightSensor)
+Fibaro Outlet (com.fibaro.FGWP101)
+Automatic status update through event mechanism

Doesn't work:
+ WINDOW_COVERING_OPERATION_STATE_CTYPE for RollerShutter

### CODE REVIEW

**Comment by dgburton** [comment]
@ilcato thanks for this! Are you planning on updating this to poll for events from the HC2 and update characteristics when they change on the HC2?

Looking here: https://developer.fibaro.com/docs/fghc-restapi it looks like the call to  /api/refreshStates is what we need.

**Comment by ilcato** [comment]
Yes

**Comment by ilcato** [comment]
Added automatic status update through event mechanism

**Comment by nfarina** [comment]
Ready to merge?

**Comment by ilcato** [comment]
Yes, it’s pretty stable now. I will continue to add support for further device but the current set is already useful.
Thanks.
Andrea

**Pull request merged**
