### PR TITLE
Fixed humidity on Nest

### PR DESCRIPTION
**Pull request by KraigM**
Fixed humidity and added change handling of settings (like Celsius/Fahrenheit).

### CODE REVIEW

**Comment by pedroserano** [comment]
Hi KraigM,

These fixes are very much welcome. I wanted to build on this to add home/away status (which could be used as a trigger in ios9) and fan on/auto read/write support, both of which seem to be exposed in the unofficial nest api, I think. I started working on the fan system and despite my best efforts have come up short. If I pasted the code, could you look at it and point me in the right direction? Would it be easier for you to add those things without also trying to debug?

**Comment by KraigM** [comment]
Awesome. Yes you can paste code and I will look at it and see if I can help you out, no problem.

**Comment by KraigM** [comment]
@pedroserano ^. Also, I don't know if you have switched to the new plugin system yet or not.  If you haven't, don't worry about it, I can help you integrate later.  But if you have, I split out nest into its own plugin: https://github.com/KraigM/homebridge-nest.  So we can maintain it better.  Feel free to send a pull request to that and I can look at it and hopefully help you out.

**Comment by pedroserano** [comment]
Yes totally! I have the new plugin system installed on my system. I will use the new address to submit a pull request.

**Pull request merged**
