### PR TITLE
Option to hide QRcode in logs

### PR DESCRIPTION
**Pull request by NebzHB**

### CODE REVIEW

**Comment by KhaosT** [comment]
Given this thing only shown once, is it really necessary? The logger one make sense as it affects all logs...

**Comment by NebzHB** [comment]
When homebridge is inserted into a graphical interface, the special chars do not display correctly, something like : [0m[40m  [0m[40m  [0m[47m  [0m[40m
that makes the logs less readable.

**Comment by KhaosT** [comment]
I understood that, but given this only happens at the beginning of the log, does it really matter?

**Comment by NebzHB** [comment]
as the accessory creation log is at the beginning of the log, it is most of case

**Comment by KhaosT** [comment]
Alright ;) In that case, would you mind to consolidate `insecureAccess` and this together as `opts` that get passed to server?
Thanks 🙏

**Comment by NebzHB** [comment]
sure

**Comment by NebzHB** [comment]
done

**Comment by NebzHB** [comment]
the sentence with "Or enter this code ..." is less good now...

**Comment by NebzHB** [comment]
fixed

**Comment by KhaosT** [comment]
Great thank you :)

**Pull request merged**
