### PR TITLE
Simplify Hue for new users

### PR DESCRIPTION
**Pull request by nfarina**
- Sample config auto-discoveres Bridge IP
- Username left blank so that the server will prompt you
- Hue platform walks you through username creation (in as friendly a
way currently possible)

/cc @stephenyeargin, #28

### CODE REVIEW

**Comment by stephenyeargin** [comment]
:+1: I think you just cleared it off @madmod's todo list :smile:

**Comment by madmod** [comment]
:+1: Looks good. I can't try it out right now, but I will test it in a few hours. I think if we could add some ability for saving to the config.json we wouldn't need to stop running if this fails.

**Comment by nfarina** [comment]
Yes agreed it would be great to have either a method for updating `config.json` (which I'm not super into, it feels wrong to fiddle with "your" config) or a method for accessory storage of preference data. Or an official method of "first time setup" for accessories. Lots to think about...

**Comment by maddox** [comment]
👎 on writing to the config
👍 to some sort of local storage (if more than 2 or 3 cases can be come up with)
👍 to not even thinking about it on this pull 😄

**Comment by maddox** [comment]
Ps: this pull is cool. Love it.

**Comment by nfarina** [comment]
Thanks but it's just icing on the cake - thanks to @stephenyeargin and @madmod for doing all the real work supporting Hue! This was the last thing in my home that wasn't hooked up to HomeKit :smile_cat:

**Pull request merged**
