### PR TITLE
Adding support for ISY.

### PR DESCRIPTION
**Pull request by rayzorben**
This adds support for Universal Devices ISY controller which communicates with an array of Insteon and Z-Wave devices. Initial commit is tested working for controlling Light Bulb (dimming), Switch, and Ceiling Fan devices. It uses the published REST API available at http://wiki.universal-devices.com/index.php?title=ISY_Developers:API:REST_Interface

### CODE REVIEW

**Comment by nfarina** [comment]
Awesome, sounds great!

**Comment by maddox** [comment]
I saw a lot of issues in this code. As mentioned [here](https://github.com/KhaosT/HAP-NodeJS/issues/91), the `onRead` was apparently not being called right.

[here](https://github.com/nfarina/homebridge/pull/37/files#diff-12025cc17baf8c499491e5def13cb0c2R256):

```js
 onRead: function() {
   return this.query();
}
```

The function isn't defined right. The function has a callback, and you're supposed to return the value with the callback, not a return.

```js
 onRead: function(callback) {
   callback(this.query());
}
```

though, `query()` wasn't defined to use a callback either, which it probably should. to keep things from blocking, (or even working correctly at all right?)

From what I can tell just by breezing over this pull though, its not exactly working.

**Comment by rayzorben** [comment]
I changed it as suggested to utilize the callback. However, I simply put a console.log in there

    onRead: function(callback) {
        console.log("Query");
        callback(this.query());
    }

I do not see the log of 'Query' ever showing up. I also log out in my query() code and it does not run either. I guess what I am asking is - when is this supposed to be executed? I never see it getting called.

**Comment by maddox** [comment]
It gets called when homekit queries the current state of your device. 

For example, ask Siri which light are on. It will get called. 

As for the logs, I'm not sure you can log via that way, I've seen them not show up like that. Check the logging pattern used in the other Accessory shims. 

Do this, instead, just return a value instead of running the query (which isn't working anyways because it doesn't support a callback). 

So just use callback(true). In the logs you should then see it.

**Comment by nfarina** [comment]
If `onRead` is not being called, then that is the first thing to investigate. From your code it does look like it's defined in the right place. This may be a silly question but did you make sure to update git submodules to get the latest version of `HAP-NodeJS`?

**Comment by rayzorben** [comment]
Really appreciate your help. Still not seeing what I think I should be seeing. Looking at the code:

    console.log("Characteristics.js:valueForUpdate(): called, Siri has asked for the accessory's status");

    if (this.onRead) {
        console.log("Characteristics.js:valueForUpdate(): invoking callback");

My log is showing the first message, but it is not showing the second message (invoking callback). I have simplified it as you recommended. I have verified that the version of HAP-NodeJS is correct and what is in Characteristic.js matches what is in your commit.

**Comment by rayzorben** [comment]
Ignore me - I pulled the latest HAP-NodeJS, but not the latest HomeBridge as I was in the middle of a commit and didn't pull it back down after. So I missed the update for the onRead to HomeBridge which copies it across. It is calling the callback now.

**Comment by nfarina** [comment]
:+1:

**Pull request merged**
