### PR TITLE
Removed submodule for HAP-NodeJS and moved to NPM

### LINKED ISSUE #51: HAP-NodeJS as npm vs submodule
Any particular reason you're including HAP-NodeJS as a submodule rather than an npm dependency? Including it as an npm dependency would simplify the installation process a bit.

### PR DESCRIPTION
**Pull request by alistairg**
It seemed to be easier all around to use NPM to manage the dependancy on HAP-NodeJS.

This PR removes the submodule, and adjusts the paths of all checked in shims to reference the NPM module instead.

I also updated the documentation to reflect the simpler install ;)

[Edit by @nfarina: Closes #51]

### CODE REVIEW

**Comment by alistairg** [comment]
Please give this a quick test before merging - I've tested fairly throughly, but it's a big change, so a code review would be appreciated ;)

**Comment by nfarina** [comment]
This is awesome! Tested and it works great for me.

One question - do you think the HAP-NodeJS dependency should be pinned to a particular commit? I worry that since it's pulling from master, someone could end up getting breaking changes.

**Comment by alistairg** [comment]
Done!

I fixed it to the current commit (handily the one I was waiting for, that added a few more characteristic types! ;p)

I also took the liberty of adding a license to your package.json, mostly to silence npm. I assumed you'd want the ISC license, but that's easily changed if wrong....

**Comment by alistairg** [comment]
Note that this also closes #51

**Comment by nfarina** [comment]
Perfect!

**Comment by maddox** [comment]
:dancer: this is great.

**Comment by madmod** [comment]
:+1: nice

**Pull request merged**
