### PR TITLE
Philips Hue integration

### LINKED ISSUE #21: [Feature] Phillips hue shim
There is a fairly robust [node module](https://github.com/peter-murray/node-hue-api) that, if I'm reading this all correctly, could be used in creating a shim. I did a [refactor](https://github.com/kingbin/hubot-philipshue/pull/8) on a Hubot module recently to use that one, so I may be able to take a look at this one.

### PR DESCRIPTION
**Pull request by stephenyeargin**
Uses the [node-hue-api](https://github.com/peter-murray/node-hue-api) package to interact with the bridge.

I've gotten it to where the devices will start appearing in Inteon+. However, when adding it, it complains that each device "does not conform" to HomeKit and removes it. I'm mostly soliciting help at this point if anyone can salvage this PR into something that works with their bridge.

- [x] Hue devices appear in HomeKit app (Insteon+)
- [x] Hue devices add to the database (without "does not conform" error)
- [x] Hue lights can be turned off/on
- [x] Hue lights can have colors changed in-app
- [x] Hue lights can have brightness changed
- [x] Hue lux lights can be turned off/on
- [x] Hue lux lights can have brightness changed
- [x] Code is cleaned up to fully use the `node-hue-api` package (instead of direct bridge calls)
- [x] Bridges can use the `detectBridges` API endpoint to further ease setup process (stretch goal)

When it merges, it fixes #21

---

Note for development: In the event Insteon+ or other application deems the device incompatible, simply delete the `./persist` directory (will nuke other things) and they will show back up on next launch.

### CODE REVIEW

**Comment by stephenyeargin** [comment]
Updated the description to outline the objectives of the PR. I'm stuck on properly registering the devices. :panda_face:

**Comment by nfarina** [comment]
I've never seen the "does not conform" error before. Are you running iOS 9?

**Comment by stephenyeargin** [comment]
Nope, standard issue iOS 8. It [appears to be specific to Insteon+](http://www.insteon.com/support-knowledgebase/2015/3/10/insteon-error-codes)

```
50, 66

The requested device does not conform to HomeKit specifications. 	

The device is not using approved HomeKit communication methods.

In some way, shape or form, the device is violating HomeKit guidelines.
```

**Comment by nfarina** [comment]
Huh, that's weird. I've found Insteon+ to be a little strange myself and haven't actually used it successfully yet. Do you have the ability to compile and deploy [BetterHomeKit](https://github.com/KhaosT/HomeKit-Demo/tree/master/BetterHomeKit) instead?

**Comment by stephenyeargin** [comment]
I ran headlong into "not having a iOS Developer Program" in getting that app to compile (something about entitlement).

screen shot 2015-06-16 at 6 09 29 pm

**Comment by stephenyeargin** [comment]
Output log when running a few of the connected lights through Insteon+

```
Starting HomeBridge server...
Loading 1 platforms...
[Phillips Hue] Initializing PhilipsHue platform...
[Phillips Hue] Fetching Philips Hue lights...
Loading 0 accessories...
[Phillips Hue] Initializing device with name Living Room (Left)...
TCP server accepting connection on port: 51826
HAP Server is listening
[Phillips Hue] Initializing device with name Living Room (Right)...
TCP server accepting connection on port: 51828
HAP Server is listening
[Phillips Hue] Initializing device with name Living Room (End Table)...
TCP server accepting connection on port: 51832
HAP Server is listening
[Phillips Hue] Initializing device with name Bedroom Overhead (1)...
TCP server accepting connection on port: 51838
HAP Server is listening
[Phillips Hue] Initializing device with name Bedroom Overhead (2)...
TCP server accepting connection on port: 51846
HAP Server is listening
[Phillips Hue] Initializing device with name Bedroom Overhead (3)...
TCP server accepting connection on port: 51856
HAP Server is listening
New Session 59385
Server Connection Established 56112
Start Pair M1
Start Pair M1
Start Pair M3
Start Pair M5
Client Disconnected
Server Disconnected
New Session 59401
New Session 59402
Server Connection Established 56133
Server Connection Established 56134
Client Disconnected
Start Verify M1
Verify M1 Finished
Server Disconnected
Start Verify M3
M3: Verify Success
Handle Remove Pairing Info
Client Disconnected
Server Disconnected
New Session 59409
Server Connection Established 56138
Start Pair M1
New Session 59410
Server Connection Established 56139
Client Disconnected
Server Disconnected
Start Pair M3
Start Pair M5
Client Disconnected
Server Disconnected
New Session 59411
New Session 59412
Server Connection Established 56141
Server Connection Established 56142
Client Disconnected
Start Verify M1
Verify M1 Finished
Server Disconnected
Start Verify M3
M3: Verify Success
Handle Remove Pairing Info
Client Disconnected
Server Disconnected
```

### Screenshots

- [Connect](https://cloud.githubusercontent.com/assets/80459/8196662/af71e384-1453-11e5-9762-5ce6114e5374.PNG)
- Prompted for Password
- [Failed](https://cloud.githubusercontent.com/assets/80459/8196661/adb5535a-1453-11e5-895c-26c41f7db087.PNG)

**Comment by stephenyeargin** [comment]
Downloaded a separate application ([MyTouchHome](http://mytouchhome.webs.com/)) and ran into the same issue. Reasonable to say it's my code that is foobar'd. :crying_cat_face: 

- [Failed](https://cloud.githubusercontent.com/assets/80459/8199190/eb5749c0-1476-11e5-89d6-042dfa4cea18.PNG)

**Comment by rayzorben** [comment]
I had this same issue developing for ISY - you HAVE to implement the POWER_STATE_CTYPE on every device, or Insteon+ complains that it does not conform. You can put in a blank onUpdate if you don't really need it to do anything, but it has to return that in the controlCharacteristics.

**Comment by madmod** [comment]
I would like to help with this. I am getting my rpi running and going over the comments and the source now. Let me know if there is anything specific you want me to look at. :smiley:

**Comment by stephenyeargin** [comment]
@rayzorben Ran it with the suggested change, same result. I'm loosely basing this shim off of [this fork](https://github.com/KhaosT/HAP-NodeJS/compare/master...renssies:master) of the underlying library that manually adds each device independently. I suspect that a) never worked, b) something has changed in the API that makes it not work or c) my translation of it carried over another flaw.

@madmod I would definitely appreciate it (and I'm sure @nfarina would as well)! I haven't had a chance to mess with it lately, but if you can review the above link and puzzle through what may have happened, I think this can be knocked out.

**Comment by rayzorben** [comment]
2 things I see different than my implementation
    1. all of my CTYPE's under the sType have supportEvents: true
    2. you don't implement the SERIAL_NUMBER cType under the information characteristics - see https://github.com/rayzorben/homebridge/blob/master/platforms/ISY.js#L203 for mine.

**Comment by stephenyeargin** [comment]
@rayzorben :exclamation::exclamation::exclamation: That may be the trick.

**Comment by stephenyeargin** [comment]
:sparkles: This is getting much closer. :sparkles:

I've tested it with the Hue lights, but I can't yet test it with the Lux lights (because my wife would be very displeased if I turn the light on at 1:30 a.m. while she's sleeping :grinning:)

**Comment by madmod** [comment]
@stephenyeargin You got it working with Hue lights then? I just tried [9814ff5](https://github.com/stephenyeargin/homebridge/commit/9814ff5525023be5be0448f6a94e19823e457adc) but I still get the "out of order" error in Insteon+. I'm going to shelve this for the night but hopefully tomorrow I can be awake enough to contribute. :sleepy:

**Comment by stephenyeargin** [comment]
I did. Incidentally, the hue/saturation/brightness scale doesn't seem to be quite right on the Insteon+ app. Not sure if this is a bug there or with my implementation of the API.

**Comment by stephenyeargin** [comment]
I also need it to understand the _initial value_ of the attributes much better. It thinks the lights are always off when the bridge first starts up.

**Comment by madmod** [comment]
I just got it working! I had unstaged changes that were silently messing up my git fetch. The color difference is a common bug with hue api implementations. Something about how philips has different color scales for different lights that don't match up with normal values. I will see if I can find out more tomorrow.

**Comment by madmod** [comment]
I think that homekit might be having a problem dealing with the maximum hue value of 65535. After changing it to a lower range and multiplying it before sending it to node-hue-api I am getting a broader color range which is closer to correct.

**Comment by stephenyeargin** [comment]
@nfarina: I believe that @madmod and I are ready to mark this one :shipit: for general use.

**Comment by nfarina** [comment]
Hey guys - I'm trying to test this with my own Hue lights, but I can't figure out how to get started. From reading the code, it looks like I can omit `ip_address` (which is good because I don't know the IP of the bridge) but now I am getting an error with my username. I entered my email address but something tells me it wants something else. How can I figure out what it needs?

**Comment by stephenyeargin** [comment]
So, I already had this from another integration, and it is a bit of a pain to obtain without familiarity with the command line -- then again, this project isn't for the faint of :heart:. Maybe we would work something like this into the instruction set?

https://github.com/kingbin/hubot-philipshue#getting-your-hue-hash

**Comment by nfarina** [comment]
OK I figured it out, got my username and it seems to work well! Watch for a PR related to username creation shortly.

**Pull request merged**
