### PR TITLE
Enhanced ISY-994i support

### PR DESCRIPTION
**Pull request by rodtoll**
I created a new platform module for supporting ISY-994i / ISY-99i from Universal Devices. 

It holds several advantages over the existing platform implementation:
- State of devices are updated automatically as they change. (Based on websocket notifications from the ISY device). 
- More devices are supported including door locks (morninglinc + zwave locks)
- A filtering system is provided to enable the list of devices to be filtered to avoid exceeding the 100 device limit.
- Elk alarm panels and sensors are supported. 

I'd like to offer this platform code to be included into the project. I'm open to you taking it and rewriting it, me changing it to meet your requirements/suggestions, you guys using it to improve the existing isy module or anything in between. I will continue to tweak the code on my end to improve my home setup and would be happy to include those in the future.

The code has been tested against my rather large personal ISY network which has almost 140 nodes including ZWave devices and a full alarm system. But of course, this code is guaranteed to do nothing but explode. :)

### CODE REVIEW

**Comment by nfarina** [comment]
This is epic; thanks for the contribution!

**Comment by nfarina** [comment]
Could you pull in the latest from master and resolve conflicts (presumably with package.json)?

**Comment by rodtoll** [comment]
Should be up to date. Also my testing found minor issue in the Elk Sensors (fixed) and in translation of alarm state (also fixed).

**Comment by nfarina** [comment]
Awesome thanks!

**Pull request merged**
