### PR TITLE
Ability to specify a specific MyQDeviceId for the Liftmaster shim

### PR DESCRIPTION
**Pull request by alistairg**
The existing Liftmaster shim works well if you have a single door opener on an account. If, however, you have multiple doors - it'll operate the first door found on the account.

By (optionally) specifying the device ID in config.json, you can restrict the control to a specific door on the target account.

### CODE REVIEW

**Comment by nfarina** [comment]
Very nice! I wonder if this might actually be better as a "Platform" instead of a single accessory - that way both door openers would appear in the "Add Accessory" list and you could pick the one(s) you want.

**Comment by alistairg** [comment]
Yeah, I considered that - I think it'll need a broader rewrite to support being a "platform". I think there's also an opportunity to cache the authentication credential to speed it up a little, and potentially "poll" for door state periodically also. I need to reverse engineer the Liftmaster website a little to see how they're doing their realtime updates.

The challenge is that you could have multiple doors at multiple locations - for example, we have one location with one door, and another with two doors, all on the same account. I don't want the doors to all show up as valid accessories in the same place.... (My issue when I first started playing with this accessory is that I expected the door at home to open when I tried it, but it in fact opened a door 70 miles away!).

**Comment by nfarina** [comment]
Oh wow. Not good!

So if I have multiple doors, how would I figure out the IDs for them for the config?

**Comment by alistairg** [comment]
Yeah, that part is kind of a pain. I suppose I could spit them out as a log entry when the shim interacts with the server…. ?

**Comment by nfarina** [comment]
Maybe something like that, yeah - right now HomeBridge doesn't have a good facility for "setup" which I'd like to work on next. But for now you could try what we're doing in the Hue shim (see #40) and just throw an exception prompting the user to enter one of the door IDs.

**Comment by alistairg** [comment]
Best bet is to likely accept it if only one door is found (straightforward, and as original author intended) but vomit with an exception with a prompt for specific door(s) if there are multiples. 

I’ll get on that after work tonight :)

**Comment by alistairg** [comment]
OK - I had a few minutes over lunch to add this ;).

If someone has only one door - it's really straightforward, the shim will select their only door and control it. If, however, they have multiple doors and one wasn't explicitly specified using the 'requiredDeviceId' config option, it'll spit out the door IDs and their names, then throw an exception.

I also added the additional possible option to config-sample.json.

**Comment by nfarina** [comment]
Beautiful, love it, thanks!

**Comment by shawc** [comment]
I have wink lights working, but can not get the lift master shim working. The only platform i have configured in the config.json file is Wink. I only have one garage door. I get the following error when i verbally issue a phrase like "Hey Siri - open the garage door. Also, i am able to open/close the garage door via my wink app when i press the garage door icon up/down.
: 
Error 'null' logging in: {"Message":"No HTTP resource was found that matches the request URI 'http://myqexternal.myqdevice.com/api/user/validatewithculture?appId=JVM%2FG9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP%2BtuPb8iHfRHKwTmDzHOu&culture=en'."}

**Comment by nfarina** [comment]
Hello - to confirm, are you controlling your garage door through Wink or did you add the LiftMaster "accessory" separately to your config.json?

**Comment by shawc** [comment]
I added the liftmaster as an accessory in my config.json file. I also updated the liftmaster.js with my liftmaster username, password and the garage door id for my door.

Sent from my iPad

On Sep 2, 2015, at 12:21 PM, Nick Farina <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello - to confirm, are you controlling your garage door through Wink or did you add the LiftMaster "accessory" separately to your config.json?

-
Reply to this email directly or view it on GitHub<https://github.com/nfarina/homebridge/pull/50#issuecomment-137177549>.


 
Confidentiality Notice: This e-mail communication and any
attachments may contain confidential and privileged information for
the use of the designated recipients named above. If you are not
the intended recipient, you are hereby notified that you have
received this communication in error and that any review,
disclosure, dissemination, distribution or copying of it or its
contents is prohibited. If you have received this communication in
error, please notify me immediately by replying to this message and
deleting it from your computer. Thank you.

**Comment by shawc** [comment]
would it be helpful if i post my config.json and listmaster.js files?

**Comment by shawc** [comment]
Here is my config.json file:
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    
    "platforms": [
        {
            "platform": "Wink",
            "name": "Wink",
            "client_id": "c893b6bd0d851bb23a07fc131c98073e",
            "client_secret": "117f308aaf98e29513812a01d2186053",
            "username": "chris.shaw@proequities.com",
            "password": "lucky5156"
        }
            ],

    "accessories": [
      {
            "accessory": "LiftMaster",
            "name": "Garage Door",
            "description": "MyQ service.",
            "username": "I deleted this for the post",
            "password" : "I deleted this for the post"
        }
    ]
}

**Comment by shawc** [comment]
here is my liftmaster.js file:
var types = require("HAP-NodeJS/accessories/types.js");
var request = require("request");

// This seems to be the "id" of the official LiftMaster iOS app
var APP_ID = "JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu"
//var APP_ID = "Vj8pQggXLhLy0WHahglCD4N1nAkkXQtGYpq2HrHD7H1nvmbT55KqtN6RSF4ILB"

function LiftMasterAccessory(log, config) {
  this.log = log;
  this.name = config["Garage Door"];
  this.username = config["i deleted this for the post"];
  this.password = config["i deleted this for the post"];
  this.requiredDeviceId = config["i deleted this for the post"];
}

LiftMasterAccessory.prototype = {

  setState: function(state) {
    this.targetState = state;
    this.login();
  },

  login: function() {
    var that = this;

    // reset our logged-in state hint until we're logged in
    this.deviceId = null;

    // querystring params
    var query = {
      appId: APP_ID,
      username: this.username,
      password: this.password,
      culture: "en"
    };

    // login to liftmaster
    request.get({
      url: "https://myqexternal.myqdevice.com/api/user/validatewithculture",
      qs: query
    }, function(err, response, body) {

      if (!err && response.statusCode == 200) {

        // parse and interpret the response
        var json = JSON.parse(body);
        that.userId = json["UserId"];
        that.securityToken = json["SecurityToken"];
        that.log("Logged in with user ID " + that.userId);
        that.getDevice();
      }
      else {
        that.log("Error '"+err+"' logging in: " + body);
      }
    });
  },

  // find your garage door ID
  getDevice: function() {
    var that = this;

    // querystring params
    var query = {
      appId: APP_ID,
      SecurityToken: this.securityToken,
      filterOn: "true"
    };

    // some necessary duplicated info in the headers
    var headers = {
      MyQApplicationId: APP_ID,
      SecurityToken: this.securityToken
    };

    // request details of all your devices
    request.get({
      url: "https://myqexternal.myqdevice.com/api/v4/userdevicedetails/get",
      qs: query,
      headers: headers
    }, function(err, response, body) {

      if (!err && response.statusCode == 200) {

        // parse and interpret the response
        var json = JSON.parse(body);
        var devices = json["Devices"];
        var foundDoors = [];

        // look through the array of devices for an opener
        for (var i=0; i<devices.length; i++) {
          var device = devices[i];

          if (device["MyQDeviceTypeName"] == "GarageDoorOpener") {

            // If we haven't explicity specified a door ID, we'll loop to make sure we don't have multiple openers, which is confusing
            if (!that.requiredDeviceId) {
              var thisDeviceId = device.MyQDeviceId;
              var thisDoorName = "Unknown";
              for (var j = 0; j < device.Attributes.length; j ++) {
                var thisAttributeSet = device.Attributes[j];
                if (thisAttributeSet.AttributeDisplayName == "desc") {
                  thisDoorName = thisAttributeSet.Value;
                  break;
                }
              }
              foundDoors.push(thisDeviceId + " - " + thisDoorName);
              that.deviceId = thisDeviceId;
            }

            // We specified a door ID, sanity check to make sure it's the one we expected
            else if (that.requiredDeviceId == device.MyQDeviceId) {
              that.deviceId = device.MyQDeviceId;
              break;
            }

          }

        }

        // If we have multiple found doors, refuse to proceed
        if (foundDoors.length > 1) {
          that.log("WARNING: You have multiple doors on your MyQ account.");
          that.log("WARNING: Specify the ID of the door you want to control using the 'requiredDeviceId' property in your config.json file.");
          that.log("WARNING: You can have multiple liftmaster accessories to cover your multiple doors");

          for (var j = 0; j < foundDoors.length; j++) {
            that.log("Found Door: " + foundDoors[j]);
          }

          throw "FATAL: Please specify which specific door this Liftmaster accessory should control - you have multiples on your account";

        }

        // Did we get a device ID?
        if (that.deviceId) {
          that.log("Found an opener with ID " + that.deviceId +". Ready to send command...");
          that.setTargetState();
        }
        else
        {
          that.log("Error: Couldn't find a door device, or the ID you specified isn't associated with your account");
        }
      }
      else {
        that.log("Error '"+err+"' getting devices: " + body);
      }
    });
  },

  setTargetState: function() {

    var that = this;
    var liftmasterState = (this.targetState + "") == "1" ? "0" : "1";

    // querystring params
    var query = {
      appId: APP_ID,
      SecurityToken: this.securityToken,
      filterOn: "true"
    };

    // some necessary duplicated info in the headers
    var headers = {
      MyQApplicationId: APP_ID,
      SecurityToken: this.securityToken
    };

    // PUT request body
    var body = {
      AttributeName: "desireddoorstate",
      AttributeValue: liftmasterState,
      ApplicationId: APP_ID,
      SecurityToken: this.securityToken,
      MyQDeviceId: this.deviceId
    };

    // send the state request to liftmaster
    request.put({
      url: "https://myqexternal.myqdevice.com/api/v4/DeviceAttribute/PutDeviceAttribute",
      qs: query,
      headers: headers,
      body: body,
      json: true
    }, function(err, response, json) {

      if (!err && response.statusCode == 200) {

        if (json["ReturnCode"] == "0")
          that.log("State was successfully set.");
        else
          that.log("Bad return code: " + json["ReturnCode"]);
          that.log("Raw response " + JSON.stringify(json));
      }
      else {
        that.log("Error '"+err+"' setting door state: " + JSON.stringify(json));
      }
    });
  },

  getServices: function() {
    var that = this;
    return [{
      sType: types.ACCESSORY_INFORMATION_STYPE,
      characteristics: [{
        cType: types.NAME_CTYPE,
        onUpdate: null,
        perms: ["pr"],
        format: "string",
        initialValue: this.name,
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "Name of the accessory",
        designedMaxLength: 255
      },{
        cType: types.MANUFACTURER_CTYPE,
        onUpdate: null,
        perms: ["pr"],
        format: "string",
        initialValue: "LiftMaster",
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "Manufacturer",
        designedMaxLength: 255
      },{
        cType: types.MODEL_CTYPE,
        onUpdate: null,
        perms: ["pr"],
        format: "string",
        initialValue: "Rev-1",
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "Model",
        designedMaxLength: 255
      },{
        cType: types.SERIAL_NUMBER_CTYPE,
        onUpdate: null,
        perms: ["pr"],
        format: "string",
        initialValue: "A1S2NASF88EW",
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "SN",
        designedMaxLength: 255
      },{
        cType: types.IDENTIFY_CTYPE,
        onUpdate: null,
        perms: ["pw"],
        format: "bool",
        initialValue: false,
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "Identify Accessory",
        designedMaxLength: 1
      }]
    },{
      sType: types.GARAGE_DOOR_OPENER_STYPE,
      characteristics: [{
        cType: types.NAME_CTYPE,
        onUpdate: null,
        perms: ["pr"],
        format: "string",
        initialValue: "Garage Door Opener Control",
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "Name of service",
        designedMaxLength: 255
      },{
        cType: types.CURRENT_DOOR_STATE_CTYPE,
        onUpdate: function(value) { that.log("Update current state to " + value); },
        perms: ["pr","ev"],
        format: "int",
        initialValue: 0,
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "BlaBla",
        designedMinValue: 0,
        designedMaxValue: 4,
        designedMinStep: 1,
        designedMaxLength: 1
      },{
        cType: types.TARGET_DOORSTATE_CTYPE,
        onUpdate: function(value) { that.setState(value); },
        perms: ["pr","pw","ev"],
        format: "int",
        initialValue: 0,
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "BlaBla",
        designedMinValue: 0,
        designedMaxValue: 1,
        designedMinStep: 1,
        designedMaxLength: 1
      },{
        cType: types.OBSTRUCTION_DETECTED_CTYPE,
        onUpdate: function(value) { that.log("Obstruction detected: " + value); },
        perms: ["pr","ev"],
        format: "bool",
        initialValue: false,
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "BlaBla"
      }]
    }];
  }
};

module.exports.accessory = LiftMasterAccessory;

**Comment by nfarina** [comment]
would you mind posting all this in a new Issue so we don't make this old PR too long? And yes, I've experience some problems with the LiftMaster shim lately, so I wouldn't be surprised if it's just not working very well right now. The API was reverse-engineered and may need to be updated.

**Comment by shawc** [comment]
Sure, i'll post a new issue. And also, a huge thanks for this project. I still can't believe i am able to issue a hey siri command and my lights turn on/off. This is unbelievably GREAT project!

**Comment by nfarina** [comment]
:smile_cat:

**Pull request merged**
