### PR TITLE
Logo for HOMEBRIDGE

### PR DESCRIPTION
**Pull request by ggabogarcia**

### CODE REVIEW

**Comment by NorthernMan54** [comment]
For storage of the logo’s, what about using github itself?  Ie add them to a repo

**Comment by ggabogarcia** [comment]
I think it would be nice to start using the logo :)

**Comment by NorthernMan54** [comment]
image

The image

**Comment by NorthernMan54** [comment]
@ggabogarcia Pls change the URL link to https://user-images.githubusercontent.com/19808920/40754647-531702de-6448-11e8-84c1-9f950d71d4cd.png

ie the address of the image in the comment above, and am wondering why the slack count was removed, can it just be moved down the page?

**Comment by ggabogarcia** [comment]
Check [this](https://i.imgur.com/r4pWjmq.png)

**Comment by ggabogarcia** [comment]
Yeap :) Although I have never used it before

**Comment by NorthernMan54** [comment]
Once your in, I can setup a direct message. Just look for me in #homebridge

**Pull request merged**
