### PR TITLE
Bump hap-nodejs to use 0.5.0

### PR DESCRIPTION
**Pull request by jedis00**
Bump hap-nodejs to use 0.5.0.

### CODE REVIEW

**Comment by nscheffer** [comment]
Why it's not updated to 0.5.0 as requested ?
We need it to support Nest CAM due to Google account migration !
Thanks in advance.

**Comment by Supereg** [comment]
any reason why homebridge still runs an outdated version of hap-nodejs? @nfarina @KhaosT

**Comment by nfarina** [comment]
Sorry, it's just for lack of testing! I'll try it out and merge shortly.

**Comment by KhaosT** [comment]
Still trying to sort out some API issues after the typescript migration 😅

**Comment by nfarina** [comment]
Yeah this PR doesn't work as-is because of some import issues.

**Comment by Supereg** [comment]
Haven't looked at the update process explicitly, though there should not have been any API changes. But homebridge is falling months behind and this should definitely be addressed.

You mentioned that you wanted to combine the dependency upgrade with the typescript migration.
There seems to exists already some proposals for that like #2266 or #2359. Are those authors still there?

**Comment by donavanbecker** [comment]
@alexindigo or @nfarina maybe this pull request should be closed in favor of @supereg’s pull request #2391.

**Comment by oznu** [comment]
Closing in favor of #2391

**Pull request closed without merging**
