### PR TITLE
fix typo `peerDepdendencies` => `peerDependencies`

### PR DESCRIPTION
**Pull request by Kosta-Github**

### CODE REVIEW

**Comment by nfarina** [comment]
Hello, this was an intentional misspelling that corrects an accidental misspelling in a very early version of the new plugin system.

**Comment by Kosta-Github** [comment]
Can you add a comment in the code then?

**Comment by luc-ass** [comment]
why don't you "replace all"?

**Comment by nfarina** [comment]
At least one plugin was already published on a Github repo that I don't control. But fear not, I believe it's updated now and I will remove this chunk of code soon.

**Pull request closed without merging**
