### PR TITLE
Noted updated for requirement to successfully get HAP-NodeJS installed.

### PR DESCRIPTION
**Pull request by derekforeman**
HAP-NodeJS was failing to build with npm install. This might help clarify for others.

### CODE REVIEW

**Comment by nfarina** [comment]
Awesome thanks!

**Comment by cflurin** [comment]
It depends of the OS. It isn't a requirement for Mac OS X.

**Comment by maddox** [comment]
Yeah, this message is pretty confusing in the README all on it's own. It has no context. "Package" has is pretty vague these days. 

It should mention that this is a Linux dependency for those using Linux (probably a pi), and should provide installation instructions: `sudo apt-get install libavahi-compat-libdnssd-dev `

**Comment by nfarina** [comment]
Good points. I hit Merge a bit too quickly there. Updated the readme in master

**Pull request merged**
