### PR TITLE
Enhancements to Nest Platform including support for range temperatures

### PR DESCRIPTION
**Pull request by KraigM**
Added several enhancements to the Nest platform:

- Updated to use the new HAP APIs (Service, Characteristic, etc)

- Used Nest subscribe system to properly notify HomeKit of any changes

- Added support for Nest's range temperatures.  Fakes it by determining the most likely main target temperature and uses that for all reads/writes until such time the other side is closer.  Its not perfect by any means but it will at least show you a proper temperature and allow you to make slight alterations without any issue.

### CODE REVIEW

**Comment by nfarina** [comment]
Awesome work!

**Comment by deejc-uk** [comment]
@KraigM i seem to have lost Humidity in EVE since this update, is this intentional ?

**Comment by KraigM** [comment]
It was causing issues at first so I removed it while I was getting everything else working.  I fixed it now in #359

**Comment by deejc-uk** [comment]
i tried git pull but got Already up-to-date.

**Comment by KraigM** [comment]
Has not been merged yet.  If you want to pull mine in to try it out:

git remote add kraigm https://github.com/KraigM/homebridge.git
git fetch kraigm
git pull kraigm/hotfix/NestHumidity

**Comment by deejc-uk** [comment]
still not working, maybe its better if i wait for the merge as i don’t really know much about git

root@omv:/opt/homebridge# git remote add kraigm https://github.com/KraigM/homebridge.git
fatal: remote kraigm already exists.
root@omv:/opt/homebridge# git fetch kraigm
root@omv:/opt/homebridge# git pull kraigm/hotfix/NestHumidity
fatal: 'kraigm/hotfix/NestHumidity' does not appear to be a git repository
fatal: The remote end hung up unexpectedly

**Pull request merged**
