### PR TITLE
Added pluginPath based on npm

### PR DESCRIPTION
**Pull request by straccio**

### CODE REVIEW

**Comment by jnovack** [comment]
There's a better way (tm).  Avoids shelling out.

```javascript
var npm = require("npm")
var myConfigObject = {}
npm.load(myConfigObject, function (er) {
    if (er) return handleError(er)
    console.log(npm.get('prefix'));
})
```

**Comment by jnovack** [comment]
All I ask is you tag one commit for credit.

`git commit -m " grab prefix via npm module" --author="Justin J. Novack <jnovack@gmail.com>"`

**Comment by straccio** [comment]
I knew this method, but i need an synchronous get.

**Comment by jnovack** [comment]
Per [`npm`](https://docs.npmjs.com/files/folders), 

> prefix Configuration
> 
> The prefix config defaults to the location where node is installed. On most systems, this is `/usr/local`, and most of the time is the same as node's `process.installPrefix`.

Try `process.installPrefix` instead?

**Comment by straccio** [comment]
I use NodeJS with nvm in OS X, process.installPrefix is undefined

**Comment by jnovack** [comment]
That should mean it's `/usr/local`. Is that not the case?

Then I'd try `process.execPath` and remove `/bin/node`.

Either way, I'd desperately shell out.

**Comment by jnovack** [comment]
FOUND IT!

`process.config.variables.node_preifx`

```
    > console.log(process.config.variables.node_prefix);
    /usr/local
```

You can have me commit some whitespace or something, feel free to take the meat and potatoes of the changes.

**Comment by straccio** [comment]
`> process.config.variables.node_prefix`
`/`
 The correct is 
`/Users/userA/.nvm/versions/node/v5.5.0/lib/node`

**Comment by jnovack** [comment]
Welp, I'm out of ideas then. I guess shelling is the only option. :-1:

**Comment by straccio** [comment]
Could resolve

**Comment by KhaosT** [comment]
Thanks :)

**Pull request merged**
