### PR TITLE
TESTING NEEDED: Sonos platform multiple devices (for #95, #153)

### PR DESCRIPTION
**Pull request by snowdd1**
Proposing idea to de-asynchronize Sonos device discovery with a **timeout event** for push-callback for #95, #153.
I have currently *no IDE and no compiler* at hand right now, so please check syntax before merging!
I have *no Sonos devices*, so please check somebody with the hardware at hand!
Thanks
Raoul

### CODE REVIEW

**Comment by iphoting** [comment]
I'm extremely new to homebridge, but I have 2 Sonos available to help smoke test. 

Here's what I did:
```bash
$ git clone https://github.com/nfarina/homebridge.git
$ cd homebridge
$ git pull https://github.com/snowdd1/homebridge.git patch-1
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/snowdd1/homebridge
 * branch            patch-1    -> FETCH_HEAD
 platforms/Sonos.js | 20 +++++++++++++++++++-
 1 file changed, 19 insertions(+), 1 deletion(-)
First, rewinding head to replay your work on top of it...
Fast-forwarded master to 1df411d916e73b73faea5787c417e1a39f69bd85.
$ npm run start
> homebridge@0.1.1 start /Users/iphoting/Development/Node.js/homebridge
> DEBUG=* node app.js || true

Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

Loading 1 platforms...
[Sonos] Initializing Sonos platform...
[Sonos] Fetching Sonos devices.
Loading 0 accessories...
[Sonos] Found device at 192.168.0.172
[Sonos] Found device at 192.168.0.173
[Sonos] Found playable device - Dining Room
[Sonos] Found playable device - Ronald's Bedroom
[Sonos] Initializing platform accessory 'Dining Room Sonos'...
[Sonos] Initializing platform accessory 'Ronald's Bedroom Sonos'...
  EventedHTTPServer Server listening on port 51826 +0ms
^C
```

It looks like it successfully detected my two Sonos devices.

Let me know what other things that I should test.

**Comment by snowdd1** [comment]
Hey it compiles! So ship it :smile: 
Frankly, this was my first javascript PR done in a text editor in a coffee break at work...

**Comment by snowdd1** [comment]
Back to serious mode: From the log you posted I see it is discovering the devices, I guess they are showing up in HomeKit app and are accessible? Then testing would be done.

You could play with the timeout setting (see the https://github.com/snowdd1/homebridge/blob/patch-1/platforms/Sonos.js#L10) `deviceDiscoveryTimeout` which I set by default to 10 seconds if not appearing in the config.json section of Sonos, to see if 10 seconds is reasoable high/low. 

Aside of that, we only have to wait until the sun rises in Oregon, USA...

**Comment by snowdd1** [comment]
I just found the author of Sonos: @bezzers could you please have a look at the PR please?

**Comment by bezzers** [comment]
I'm not in a position to test for a few days, but the logic looks sound. I'm not sure what has changed to break the old version but it is probably better to push everything at once anyway.

**Comment by nfarina** [comment]
Good morning from Oregon USA :sunrise:

**Pull request merged**
