### PR TITLE
Added WindowCovering

### PR DESCRIPTION
**Pull request by FischerRo**
Added some lines to support Shutter as WindowCovering (EnOcean). 
Tested with Eltako FSB61NB and fhem.pl 9307 (2015-09-25).
May require more work for additional windowConvering properties.

### CODE REVIEW

**Comment by justme-1968** [comment]
i just saw your pull request for the eltako actor. great. but i think the way it is done is not optimal.

i would like to suggest the following changes:
- also use mappings.blind instead of adding an additional mappings.windowCovering
   the idea is that there is one mapping per device/service type and for different fhem actors 
   the correct reading and commands are set. the same would apply to mappings.motor
- maybe renaming it to blind to windowCovering would be good though.
- i think for most devices there should be no hard coded dependency on the fhem device type but
  rather the genericDeviceType attribute should be used. but i'm thinking about having a generic
  mapping of device type/device attributtes so that the code itself will contain less dependencies.

could you please send me an jsonlist2 from the device and describe wich readings contain the motor direction.

**Comment by FischerRo** [comment]
happy to discuss improvements. agree on not using hard-coded dependencies. will update.

Motor doesn't seem to have direction. 
Actor supports cmds "up", "down", "position xx", "stop". 
Sets also defines "opens", "closes". Haven't seen FHEM set these values in any of the readings though. 

Guess using eep (enocean-profile) would help. But "eep": "A5-3F-7F" seems to be "Universal" (see https://www.enocean.com/fileadmin/redaktion/enocean_alliance/pdf/EnOcean_Equipment_Profiles_EEP_V2.6.2_public.pdf)


=== JSON SNIPPET ===

{
  "Name": "wz_rollo_r",
  "PossibleSets": "closes:noArg down opens:noArg position:slider,0,5,100 stop:noArg teach:noArg up",
  "PossibleAttrs": "verbose:0,1,2,3,4,5 room group comment alias eventMap userReadings IODev do_not_notify:1,0 ignore:0,1 dummy:0,1 showtime:1,0 actualTemp angleMax:slider,-180,20,180 alarmAction:no,stop,opens,closes angleMin:slider,-180,20,180 angleTime setCmdTrigger:man,refDev blockUnknownMSC:no,yes blockMotion:no,yes blockTemp:no,yes blockDisplay:no,yes blockDateTime:no,yes blockTimeProgram:no,yes blockOccupancy:no,yes blockSetpointTemp:no,yes blockFanSpeed:no,yes blockKey:no,yes comMode:confirm,biDir,uniDir daylightSavingTime:supported,not_supported dataEnc:VAES,AES-CBC defaultChannel:all,input,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29 demandRespAction demandRespRefDev demandRespMax:A0,AI,B0,BI,C0,CI,D0,DI demandRespMin:A0,AI,B0,BI,C0,CI,D0,DI demandRespRandomTime demandRespThreshold:slider,0,1,15 demandRespTimeoutLevel:max,last destinationID devChannel devMode:master,slave devUpdate:off,auto,demand,polling,interrupt dimMax dimMin dimValueOn disable:0,1 disabledForIntervals displayContent:default,humidity,off,setPointTemp,tempertureExtern,temperatureIntern,time,no_change eep gpDef gwCmd:blindCmd,controlVar,dimming,fanStage,setpointBasic,setpointShift,switching humitity humidityRefDev keyRcv keySnd macAlgo:no,3,4 manufID:000,001,002,003,004,005,006,007,008,009,00A,00B,00C,00D,00E,00F,010,011,012,013,014,015,016,017,018,019,01A,01B,01C,01D,01E,01F,020,021,022,023,024,025,026,027,028,029,02A,02B,02C,02D,030,031,032,033,034,035,036,038,039,03A,03C,03E,03F,040,041,7FF model:other,FAE14,FHK14,FHK61,FSA12,FSB14,FSB61,FSB70,FSM12,FSM61,FT55,FTS12 observe:on,off observeCmdRepetition:1,2,3,4,5 observeErrorAction observeInterval observeLogic:and,or observeRefDev pollInterval productID rampTime releasedChannel:A,B,C,D,I,0,auto repeatingAllowed:yes,no remoteManagement:off,on rlcAlgo:no,2++,3++ rlcRcv rlcSnd rlcTX:true,false reposition:directly,opens,closes scaleDecimals:0,1,2,3,4,5,6,7,8,9 scaleMax scaleMin secMode:rcv,snd,bidirsecCode secLevel:encapsulation,encryption,off sendDevStatus:no,yes sensorMode:switch,pushbutton serviceOn:no,yes shutTime shutTimeCloses subDef subDef0 subDefI subDefA subDefB subDefC subDefD subType:CO2Sensor.01,COSensor.01,COSensor.02,FRW,HSensor.01,PM101,actuator.01,autoMeterReading.00,autoMeterReading.01,autoMeterReading.02,autoMeterReading.03,autoMeterReading.04,autoMeterReading.05,autoMeterReading.10,baroSensor.01,blindsCtrl.00,contact,currentClamp.00,currentClamp.01,currentClamp.02,digitalInput.01,digitalInput.02,digitalInput.03,digitalInput.04,digitalInput.05,energyManagement.01,environmentApp,fanCtrl.00,gateway,genericProfile,hvac.01,hvac.10,hvac.11,keycard,ledCtrlState.00,ledCtrlState.01,lightCtrl.01,lightCtrlState.01,lightCtrlState.02,lightSensor.01,lightSensor.02,lightSensor.03,lightTempOccupSensor.01,lightTempOccupSensor.02,lightTempOccupSensor.03,liquidLeakage,manufProfile,multiFuncSensor,occupSensor.01,occupSensor.02,occupSensor.03,particlesSensor.01,radiationSensor.01,radonSensor.01,raw,roomCtrlPanel.00,roomSensorControl.01,roomSensorControl.02,roomSensorControl.05,roomSensorControl.18,roomSensorControl.19,roomSensorControl.1A,roomSensorControl.1B,roomSensorControl.1C,roomSensorControl.1D,roomSensorControl.1F,roomSensorControl.20,shutterCtrlState.01,switch,switch.00,switch.7F,tempCtrlState.01,tempHumiCO2Sensor.01,tempHumiSensor.02,tempHumiSensor.03,tempSensor.01,tempSensor.02,tempSensor.03,tempSensor.04,tempSensor.05,tempSensor.06,tempSensor.07,tempSensor.08,tempSensor.09,tempSensor.0A,tempSensor.0B,tempSensor.10,tempSensor.11,tempSensor.12,tempSensor.13,tempSensor.14,tempSensor.15,tempSensor.16,tempSensor.17,tempSensor.18,tempSensor.19,tempSensor.1A,tempSensor.1B,tempSensor.20,tempSensor.30,valveCtrl.00,vocSensor.01,windowHandle,windowHandle.10 subTypeSet:CO2Sensor.01,COSensor.01,COSensor.02,FRW,HSensor.01,PM101,actuator.01,autoMeterReading.00,autoMeterReading.01,autoMeterReading.02,autoMeterReading.03,autoMeterReading.04,autoMeterReading.05,autoMeterReading.10,baroSensor.01,blindsCtrl.00,contact,currentClamp.00,currentClamp.01,currentClamp.02,digitalInput.01,digitalInput.02,digitalInput.03,digitalInput.04,digitalInput.05,energyManagement.01,environmentApp,fanCtrl.00,gateway,genericProfile,hvac.01,hvac.10,hvac.11,keycard,ledCtrlState.00,ledCtrlState.01,lightCtrl.01,lightCtrlState.01,lightCtrlState.02,lightSensor.01,lightSensor.02,lightSensor.03,lightTempOccupSensor.01,lightTempOccupSensor.02,lightTempOccupSensor.03,liquidLeakage,manufProfile,multiFuncSensor,occupSensor.01,occupSensor.02,occupSensor.03,particlesSensor.01,radiationSensor.01,radonSensor.01,raw,roomCtrlPanel.00,roomSensorControl.01,roomSensorControl.02,roomSensorControl.05,roomSensorControl.18,roomSensorControl.19,roomSensorControl.1A,roomSensorControl.1B,roomSensorControl.1C,roomSensorControl.1D,roomSensorControl.1F,roomSensorControl.20,shutterCtrlState.01,switch,switch.00,switch.7F,tempCtrlState.01,tempHumiCO2Sensor.01,tempHumiSensor.02,tempHumiSensor.03,tempSensor.01,tempSensor.02,tempSensor.03,tempSensor.04,tempSensor.05,tempSensor.06,tempSensor.07,tempSensor.08,tempSensor.09,tempSensor.0A,tempSensor.0B,tempSensor.10,tempSensor.11,tempSensor.12,tempSensor.13,tempSensor.14,tempSensor.15,tempSensor.16,tempSensor.17,tempSensor.18,tempSensor.19,tempSensor.1A,tempSensor.1B,tempSensor.20,tempSensor.30,valveCtrl.00,vocSensor.01,windowHandle,windowHandle.10 subTypeReading:CO2Sensor.01,COSensor.01,COSensor.02,FRW,HSensor.01,PM101,actuator.01,autoMeterReading.00,autoMeterReading.01,autoMeterReading.02,autoMeterReading.03,autoMeterReading.04,autoMeterReading.05,autoMeterReading.10,baroSensor.01,blindsCtrl.00,contact,currentClamp.00,currentClamp.01,currentClamp.02,digitalInput.01,digitalInput.02,digitalInput.03,digitalInput.04,digitalInput.05,energyManagement.01,environmentApp,fanCtrl.00,gateway,genericProfile,hvac.01,hvac.10,hvac.11,keycard,ledCtrlState.00,ledCtrlState.01,lightCtrl.01,lightCtrlState.01,lightCtrlState.02,lightSensor.01,lightSensor.02,lightSensor.03,lightTempOccupSensor.01,lightTempOccupSensor.02,lightTempOccupSensor.03,liquidLeakage,manufProfile,multiFuncSensor,occupSensor.01,occupSensor.02,occupSensor.03,particlesSensor.01,radiationSensor.01,radonSensor.01,raw,roomCtrlPanel.00,roomSensorControl.01,roomSensorControl.02,roomSensorControl.05,roomSensorControl.18,roomSensorControl.19,roomSensorControl.1A,roomSensorControl.1B,roomSensorControl.1C,roomSensorControl.1D,roomSensorControl.1F,roomSensorControl.20,shutterCtrlState.01,switch,switch.00,switch.7F,tempCtrlState.01,tempHumiCO2Sensor.01,tempHumiSensor.02,tempHumiSensor.03,tempSensor.01,tempSensor.02,tempSensor.03,tempSensor.04,tempSensor.05,tempSensor.06,tempSensor.07,tempSensor.08,tempSensor.09,tempSensor.0A,tempSensor.0B,tempSensor.10,tempSensor.11,tempSensor.12,tempSensor.13,tempSensor.14,tempSensor.15,tempSensor.16,tempSensor.17,tempSensor.18,tempSensor.19,tempSensor.1A,tempSensor.1B,tempSensor.20,tempSensor.30,valveCtrl.00,vocSensor.01,windowHandle,windowHandle.10 summerMode:off,on switchMode:switch,pushbutton switchHysteresis switchType:direction,universal,channel,central temperatureRefDev temperatureScale:C,F,default,no_change timeNotation:12,24,default,no_change timeProgram1 timeProgram2 timeProgram3 timeProgram4 updateState:default,yes,no uteResponseRequest:yes,no event-on-change-reading event-on-update-reading event-aggregator event-min-interval stateFormat cmdIcon devStateIcon devStateStyle icon sortby webCmd widgetOverride userattr",
  "Internals": {
    "DEF": "<ID>",
    "NAME": "wz_rollo_r",
    "NR": "21",
    "NTFY_ORDER": "50-wz_rollo_r",
    "STATE": "0",
    "TYPE": "EnOcean"
  },
  "Readings": {
    "anglePos": {
      "Value": "0",
      "Time": "2015-10-01 19:24:41"
    },
    "endPosition": {
      "Value": "open",
      "Time": "2015-10-01 19:24:41"
    },
    "position": {
      "Value": "0",
      "Time": "2015-10-01 19:24:41"
    },
    "state": {
      "Value": "stop",
      "Time": "2015-10-01 19:06:22"
    },
    "teach": {
      "Value": "4BS teach-in sent",
      "Time": "2015-09-11 17:31:54"
    }
  },
  "Attributes": {
    "IODev": "TCM_ESP3_0",
    "comMode": "confirm",
    "eep": "A5-3F-7F",
    "manufID": "00D",
    "model": "FSB61",
    "room": "Wohnzimmer",
    "shutTime": "30",
    "shutTimeCloses": "31",
    "stateFormat": "position",
    "subDef": "FFA4F081",
    "subType": "manufProfile"
  }
}

**Comment by justme-1968** [comment]
for homematic motor is the reading that can have up/down and indicates the direction the bild is moving. so i have named it mappings.motor. 

what values can be in state during movement?

**Comment by FischerRo** [comment]
as for my environment - the readings.state doesn't change while motor is in movement. state value remains "stop". In fact, the value will only update if a stop cmd is sent. 

Why do we need the direction of the motor?

**Comment by justme-1968** [comment]
we don't realy need motor but the position state characteristic is mandatory. without any input it will always show stopped.

i will add it to the comment section and also automatically add it to the userAttributes on startup.

**Comment by justme-1968** [comment]
one more thing: you did not set mappings.blind.cmd so the should result in an error if you try to set the position with homekit. am i missing something ?

**Comment by justme-1968** [comment]
i have added a slightly simpler version to  my git repository. please try if have not forgotten anything.

**Comment by FischerRo** [comment]
sorry. took me a while. works nicely. thanks! You still might want to add a note that reminds user to add the genericDeviceType attribute to FHEM (see my last commit).

**Comment by justme-1968** [comment]
i will integrate that the genericDeviceType attribute ist automatically added to fhem if it is not available.

if everything works you could close this pull request.

**Pull request closed without merging**
