### PR TITLE
Change hosting of Logo to homebridge itself

### PR DESCRIPTION
**Pull request by NorthernMan54**
Current one was raising a security issue with Chrome

Placed a copy of the image in #1865

### CODE REVIEW

**Comment by KhaosT** [comment]
🙏

**Comment by NorthernMan54** [comment]
@ebaauw @nfarina @oznu gets the credit here, he noticed that the logo was triggering security alerts in Chrome.  Moved the hosting the GitHub itself in issue #1865

**Comment by oznu** [comment]
Thanks @NorthernMan54.

Yes, this is what is currently showing in chrome on npm:

image

This does not occur on GitHub as they proxy the images (probably to protect users privacy and https-ify all the content).

Security report:

https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fd3a1eqpdtt5fg4.cloudfront.net%2Fitems%2F2g3V1J0o0E3m393M3Z1w%2FLogo2x.png&hl=en-GB

`https://cl.ly/99e68ac49cef/Logo2x.png` redirects to `https:%2F%2Fd3a1eqpdtt5fg4.cloudfront.net%2Fitems%2F2g3V1J0o0E3m393M3Z1w%2FLogo2x.png`

**Comment by KhaosT** [comment]
Pushed 0.4.50 with the change, now https://www.npmjs.com/package/homebridge should work correctly :)

**Comment by oznu** [comment]
Confirmed it does. Thanks @KhaosT!

**Comment by nfarina** [comment]
Ah whoops, thanks all!

**Pull request merged**
