### PR TITLE
Bridge support

### PR DESCRIPTION
**Pull request by alistairg**
Bridge support enables a platform to run all its accessories with a single PIN. Accessories added with subsequent starts should automatically show on iOS devices that are paired with the top level bridge accessory.

Changes:
1. Added "bridges" directory
2. Altered app.js to support loading bridges at startup
3. Adjusted PhilipsHue.js as a bridge platform. This may be unnecessary - the only difference is that the export is now "bridge" rather than platform
4. Added config-sample.json bridge sample

Note that I had to move some code around to get the requires and global tracking variables in the right places....

References #58

### CODE REVIEW

**Comment by madmod** [comment]
Looks good to me. :shipit:

**Comment by nfarina** [comment]
So this is great! Some concerns though - main one is that this doesn't solve the "stable accessory ID" problem referenced in [this comment](/nfarina/homebridge/issues/58#issuecomment-119024143). If accessories are added or removed behind the bridge, the user will need to remove the bridge entirely and re-add it (they'll also need to delete the `persist` directory to work around a bug with HAP-NodeJS).

In order to fix this we'll need to do some thinking about how to enforce stable accessory IDs and patch support for that into `HAP-NodeJS` if necessary.

Also I think it's not ideal to have a 3rd "bucket" for accessories in config.json - I'd actually rather standardize on _everything_ being bridged behind the scenes, and possibly eliminating standalone "accessories" altogether (see [roadmap discussion on that](https://github.com/nfarina/homebridge/wiki/Roadmap)).

For stable IDs - does each Hue bulb have some kind of hardcoded unchanging identifier we could leverage?

**Comment by madmod** [comment]
The each bulb has a unique ID which is given as the `SERIAL_NUMBER_CTYPE` currently.

**Comment by nfarina** [comment]
I wonder if unique serial numbers would make stable accessory IDs unnecessary. It's worth testing; my previous tests were with HAP-NodeJS's "sample accessories" which all have the same fake serial number.

**Comment by madmod** [comment]
I think a bridge MAC address combined with a device ID and maybe a model number would be enough for devices that don't give a unique I'd like Hue. Assuming that the device ID is stable.

**Comment by alistairg** [comment]
I'm going to kill this PR - this is too buggy in this format.... it shouldn't go into the mainline code. Apologies for the excited checkin!

**Comment by nfarina** [comment]
No worries, it should be useful when we do this for real :) I'd just like to do a bit more testing to be 100% sure that stable accessory IDs are required. In my previous test all accessories shared the same default MAC identifier, so it's possible that if the MACs are unique (as they should be in real life) that the accessory IDs can change.

**Pull request closed without merging**
