### PR TITLE
Print scannable setup code to terminal on startup

### PR DESCRIPTION
**Pull request by Cosmo**
This prints the pin code from the config to the terminal in a scannable format.
I was missing this from the first time I've installed homebridge ;)

Here's a example video of what it does:
[Setup Code](http://www.youtube.com/watch?v=JYHM4FtCSbw)

### CODE REVIEW

**Comment by nfarina** [comment]
OMG BRILLIANT

**Comment by nfarina** [comment]
I wonder if the call to `printPin` would be better placed in the `publish()` method just before publishing the bridge - that way it won't scroll out of view while all your accessories/platforms are (verbosely) loading.

**Comment by justme-1968** [comment]
great.

yes. it would be better at behind publish. there can be many many lines of output if a platform shim is used.

**Comment by maddox** [comment]
THIS IS WONDERFUL!! Thanks!

**Comment by snowdd1** [comment]
:+1:

> Am 17.09.2015 um 17:19 schrieb Jon Maddox - notifications@github.com <snowdd1.theelk.6452e6e747.notifications#github.com@ob.0sg.net>:
> 
> THIS IS WONDERFUL!! Thanks!
>

**Comment by Cosmo** [comment]
Done!

**Comment by KhaosT** [comment]
Awesome 👏

**Comment by nfarina** [comment]
So, so cool. Thanks for this!

**Comment by cflurin** [comment]
@Cosmo: not only cool but also useful. Thanks.

For OS X I had to set the color this way:
```javascript
  var color = "\x1b[30\x1b[47\x1b[0m"; // "\x1b[30;47m%s\x1b[0m"
  console.log("Scan this code with your HomeKit App on your iOS device:");
  console.log(color, "                       ");
  console.log(color, "    ┌────────────┐     ");
  console.log(color, "    │ " + pin + " │     ");
  console.log(color, "    └────────────┘     ");
  console.log(color, "                       ");
```

**Comment by Cosmo** [comment]
@cflurin
Now I feel stupid for not using a variable for the escape sequences :grinning:

No color is needed? How does your terminal look like?
I couldn't get my iPhone to scan the setup code on a black background with green text.
Tried different angles, font sizes, no luck :(

**Comment by cflurin** [comment]
@Cosmo: I got a gray background

terminal

I'm using the Basic-Profile for the Terminal, which has white-background.

**Comment by Cosmo** [comment]
That explains why you don't need color :)

**Comment by cflurin** [comment]
I didn't try but maybe "Light White" could be better:
```javascript
var color = "\x1b[107;30m%s\x1b[0m";
```

**Comment by SphtKr** [comment]
Awesome, I thought of something like this but figured you'd have to have the little logo, which would run afoul of trademarks...didn't even think of trying it without!

**Comment by Cosmo** [comment]
hey @cflurin, your white looks much better! is this a standard?

**Comment by cflurin** [comment]
@Cosmo: take a look at: https://en.wikipedia.org/wiki/ANSI_escape_code#Colors
I don't really unterstand the difference between normal and light white! White should be RGB FF,FF,FF.
Anyway on my RPi the code 107 instead of 47 is actually "white".

**Pull request merged**
