### PR TITLE
Enhanced and Fixed Logitech Harmony

### PR DESCRIPTION
**Pull request by KraigM**
I started with what @enriquez had done, fixed a few more things, changed it to use the new HAP API's, and enhanced. 

- LogitechHarmonyAccessory now bases off HAP's Accessory and utilizes new Service and Characteristic API's

- Uses the loop that @enriquez added to update the state of which activity is "On" 

- Turning activity "Off" now just changes the activity to the "Power Off" activity

- Properly responds to HomeKit set calls (waits for Harmony to finish and completes callback with updated state)

- Added extra handling for connection loss

### CODE REVIEW

**Comment by nfarina** [comment]
Could you pull latest from master and fix conflicts? Probably just a package.json thing. Also will need @enriquez or @madmod's signoff as I have no idea how this accessory works :)

**Comment by KraigM** [comment]
Yeah, my last changeset was supposed to handle any conflicts, but git still got scared because a line was added right next to a line that was removed lol.

**Comment by nfarina** [comment]
Anyone else using the Harmony platform that can test this PR? The code looks great to me but I don't own any devices :)

**Comment by fitzage** [comment]
I'd be happy to test if I knew how. Have any instructions for how I can get this pull request pulled locally for testing?

**Comment by julianfez** [comment]
Sure i would lime to try it

**Comment by KraigM** [comment]
git remote add kraigm https://github.com/KraigM/homebridge.git
git fetch kraigm
git checkout -b feature/Harmony kraigm/feature/Harmony

**Comment by madmod** [comment]
Thanks for the pr, I will give it a try with my Harmony

**Comment by fitzage** [comment]
Just tested. Fixed the crashes, and I was able to successfully activate an activity and then turn it off from the El Gato Eve app. Haven't yet figured out how to make Siri do it (it just googled "turn on Apple TV" when I tried that), but it works.

**Comment by fitzage** [comment]
"Turn on Watch TV" worked, so maybe I just need to change the name of my Apple TV activity or something.

**Comment by madmod** [comment]
I'm having an error with `node-stringprep` when I install the packages so I can't test it until I get it running on a PI tonight.

**Comment by fitzage** [comment]
I do get the node-stringprep error mentioned by @madmod, but it doesn't appear to actually prevent anything from working.
```
  node-stringprep Cannot load StringPrep-0.7.2 bindings (using fallback). You may need to `npm install node-stringprep` +0ms
  node-stringprep Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/fitzage/Source/homebridge/node_modules/node-stringprep/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/fitzage/Source/homebridge/node_modules/node-stringprep/index.js:10:39)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32) +1ms
  node-stringprep Cannot load StringPrep-0.7.2 bindings (using fallback). You may need to `npm install node-stringprep` +0ms
  node-stringprep Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/fitzage/Source/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/node_modules/node-stringprep/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/fitzage/Source/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/node_modules/node-stringprep/index.js:10:39)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32) +0ms
```

**Comment by nfarina** [comment]
@KraigM What's the StringPrep thing? should that be added to the global package.json?

**Comment by KraigM** [comment]
I don't use it but harmonyhubjs-client does use it.  I have not had any issues with it myself.  I did go ahead and update to the officially released version of the package, since the repo admin finally approved/merged released @enriquez's fix.  Maybe that will help?  Also try deleting your node_modules before npm install

**Comment by fitzage** [comment]
I updated and removed my node modules, but I still get the same stringprep error.

**Comment by KraigM** [comment]
Do you get the error on npm install or is this happing at runtime? If runtime, do you get any errors/warnings on npm install?

**Comment by fitzage** [comment]
I did not see any errors during npm install that I noticed. This is a runtime error, but it doesn't prevent anything from working as far as I can tell.

**Comment by KraigM** [comment]
Just out of curiosity, try running "npm install node-stringprep" at the root of homebridge and see if that fixes it.  If so, a work around could be to add that dependency to homebridge to enforce this.  

The only thing special I noticed is that that package is used with several diff versions throughout the harmony packages (nested) and also it has to be node-gyp rebuilt so it could act diff on diff platforms.  What platform are you using?

**Comment by fitzage** [comment]
I did try manually installing it. No change.

I'm running on Mac OS.

**Comment by KraigM** [comment]
I'm running mac as well but I didn't have full debug info on (I used 'node app.js').  I get the same message but it doesn't effect me either.  Seems to work just fine.  Also it was reported in #131 so it doesn't seem to be unique to my changes.

**Comment by KraigM** [comment]
I finally got my RPi setup (I have been running it via an IDE on my mbp retina) and I have it working on both.

SideNote: I learned the hard way that you have to use a different hub config if you try using a different computer (even if you only run one at a time).  iOS must keep track of MAC Address' or something and deny hub connection if it does not match.

**Comment by nfarina** [comment]
Ok then I am good with merging if you think it's ready @KraigM

**Comment by KraigM** [comment]
Yeah I think its good to go.  Should hopefully fix some of the other issues written up in the issue tracker.  If not or it introduces new issues, I would be happy to help.

**Comment by nfarina** [comment]
Awesome.

**Pull request merged**
